"""
candidates_writer.py — Generate candidates.md from the candidates DB table.

Called after morning brief synthesis. Output is sorted by conviction score
descending. candidates.md is gitignored — machine-generated, read-only.

Usage:
    python parsers/candidates_writer.py [--dry-run]
"""

import logging
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DB_PATH = BASE_DIR / "data" / "newsfeed.db"
CANDIDATES_PATH = BASE_DIR / "candidates.md"
LOG_PATH = BASE_DIR / "logs" / "candidates_writer.log"

LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    handlers=[
        logging.FileHandler(LOG_PATH),
        logging.StreamHandler(sys.stdout),
    ],
)
log = logging.getLogger(__name__)


def table_exists(conn: sqlite3.Connection, table: str) -> bool:
    row = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name=?", (table,)
    ).fetchone()
    return row is not None


def write_candidates_md(conn: sqlite3.Connection) -> Path:
    if not table_exists(conn, "candidates"):
        log.info("candidates table does not exist — nothing to write")
        return CANDIDATES_PATH

    rows = conn.execute(
        """
        SELECT ticker, company_name, conviction_score, macro_score, fundamentals_score,
               thesis, source_name, first_seen, status
        FROM candidates
        WHERE status = 'active'
        ORDER BY conviction_score DESC, ticker ASC
        """
    ).fetchall()

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = [
        f"# Candidates — generated {today}",
        "",
        "<!-- Auto-generated by candidates_writer.py — do not hand-edit -->",
        "",
        "| Ticker | Company | Conviction | Macro | Fund. | Thesis Summary | Source | Added |",
        "|--------|---------|-----------|-------|-------|----------------|--------|-------|",
    ]

    for row in rows:
        ticker, company, conviction, macro, fund, thesis, source, first_seen, status = row
        thesis_short = (thesis or "")[:60] + ("…" if thesis and len(thesis) > 60 else "")
        company = company or ""
        conviction = conviction or 0
        macro = macro or 0
        fund = fund or 0
        source = source or ""
        added = (first_seen or "")[:10]
        lines.append(
            f"| {ticker} | {company} | {conviction} | {macro} | {fund} | {thesis_short} | {source} | {added} |"
        )

    if not rows:
        lines.append("| — | — | — | — | — | No active candidates | — | — |")

    lines.append("")
    content = "\n".join(lines)
    CANDIDATES_PATH.write_text(content)
    log.info("Wrote %d candidates to %s", len(rows), CANDIDATES_PATH)
    return CANDIDATES_PATH


def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(description="Generate candidates.md from DB")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if not DB_PATH.exists():
        log.error("DB not found at %s", DB_PATH)
        sys.exit(1)

    conn = sqlite3.connect(DB_PATH)
    if args.dry_run:
        if not table_exists(conn, "candidates"):
            log.info("candidates table does not exist")
        else:
            rows = conn.execute(
                "SELECT ticker, conviction_score FROM candidates WHERE status='active' ORDER BY conviction_score DESC"
            ).fetchall()
            log.info("DRY RUN: %d active candidates", len(rows))
            for r in rows:
                print(f"  {r[0]}  conviction={r[1]}")
    else:
        write_candidates_md(conn)
    conn.close()


if __name__ == "__main__":
    main()
